export const SET_COMPANY_LIST_LOADING = 'SET_COMPANY_LIST_LOADING'
export const SET_COMPANIES_LIST = 'SET_COMPANIES_LIST'
export const SET_SELECTED_COMPANIES_LIST = 'SET_SELECTED_COMPANIES_LIST'

export const SET_SELECTED_ASSETS_TYPES = 'SET_SELECTED_ASSETS_TYPES'

export const SET_ASSETS_COMPANIES_LOADING = 'SET_ASSETS_COMPANIES_LOADING'
export const SET_ASSETS_COMPANIES = 'SET_ASSETS_COMPANIES'
export const SET_SELECTED_ASSETS_COMPANIES = 'SET_SELECTED_ASSETS_COMPANIES'

export const SET_ASSETS_CUSTOMERS_LOADING = 'SET_ASSETS_CUSTOMERS_LOADING'
export const SET_ASSETS_CUSTOMERS_LOADING_MORE = 'SET_ASSETS_CUSTOMERS_LOADING_MORE'

export const SET_ASSETS_CUSTOMERS = 'SET_ASSETS_CUSTOMERS'
export const SET_SELECTED_ASSETS_CUSTOMERS = 'SET_SELECTED_ASSETS_CUSTOMERS'

export const SET_ASSETS_TRANSACTIONS_LOADING = 'SET_ASSETS_TRANSACTIONS_LOADING'
export const SET_ASSETS_TRANSACTIONS = 'SET_ASSETS_TRANSACTIONS'
export const SET_SELECTED_ASSETS_TRANSACTIONS = 'SET_SELECTED_ASSETS_TRANSACTIONS'

export const SET_ASSETS_TRANSACTIONS_LIFE_SPAN ='SET_ASSETS_TRANSACTIONS_LIFE_SPAN'

export const SET_ASSETS_PATENTS_LOADING = 'SET_ASSETS_PATENTS_LOADING'
export const SET_ASSETS_PATENTS = 'SET_ASSETS_PATENTS'
export const SET_SELECTED_ASSETS_PATENTS = 'SET_SELECTED_ASSETS_PATENTS'

export const SET_ASSETS_ILLUSTRATION_LOADING = 'SET_ASSETS_ILLUSTRATION_LOADING'
export const SET_ASSETS_USPTO_LOADING = 'SET_ASSETS_USPTO_LOADING'
export const SET_ASSET_ILLUSTRATION = 'SET_ASSET_ILLUSTRATION'
export const SET_ASSETS_USPTO = 'SET_ASSETS_USPTO'

export const SET_COMMENTS_ENTITY = 'SET_COMMENTS_ENTITY'

export const SET_PDF_FILE = 'SET_PDF_FILE'
export const SET_PDF_VIEW = 'SET_PDF_VIEW'
export const SET_PDF_VIEW_MODAL = 'SET_PDF_VIEW_MODAL'
export const SET_PDF_TAB = 'SET_PDF_TAB'

export const SET_CONNECTION_DATA ='SET_CONNECTION_DATA'
export const SET_CONNECTION_VIEW_BOX ='SET_CONNECTION_VIEW_BOX'

