export const SET_LAST_ERRORS_COUNT_TIME = 'SET_LAST_ERRORS_COUNT_TIME'
export const SET_LAST_RECORDS_COUNT_TIME = 'SET_LAST_RECORDS_COUNT_TIME'
export const SET_LAST_COMPLETED_COUNT_TIME = 'SET_LAST_COMPLETED_COUNT_TIME'

export const SET_ASSETS_ERRORS_DATA = 'SET_ASSETS_ERRORS_DATA'
export const SET_IS_LOADING_ASSETS_ERRORS_DATA = 'SET_IS_LOADING_ASSETS_ERRORS_DATA'
export const SET_SELECTED_ASSETS_ERRORS = 'SET_SELECTED_ASSETS_ERRORS'

export const SET_IS_LOADING_ASSETS_RECORDS_DATA = 'SET_IS_LOADING_ASSETS_RECORDS_DATA'
export const SET_ASSETS_RECORDS_DATA = 'SET_ASSETS_RECORDS_DATA'
export const SET_SELECTED_ASSETS_RECORDS = 'SET_SELECTED_ASSETS_RECORDS'

export const SET_ASSETS_COMPLETED_DATA = 'SET_ASSETS_COMPLETED_DATA'
export const SET_IS_LOADING_ASSETS_COMPLETED_DATA = 'SET_IS_LOADING_ASSETS_COMPLETED_DATA'
export const SET_SELECTED_ASSETS_COMPLETED = 'SET_SELECTED_ASSETS_COMPLETED'


