export default {
  auth: {
    auth_email_sent: false,
    isLoadingReset: true,
    password_reset: false,
    redirect_page: false,
  },
  patient: {
    currentWidget: 'all',
    customersData: {
      'acquisitions': [],
      'sales': [], 
      'licenseIn': [], 
      'licenseOut': [], 
      'securities': [], 
      'mergerin': [], 
      'mergerout': [],
      'options': [], 
      'courtOrders': [], 
      'employees': [], 
      'other': []
    }, 
    connectionBoxData: {},
    connectionBoxView: false,
    pdfFile: { document: '', form: '', agreement: '' },
    pdfTab: 0,
    pdfView: false,
    settingText: 'Settings',
    portfolio_company: null,
    portfolio_company_customer: null,
    record_item: null,
    customersLoading: false,
    treeCompanySelected: undefined,
    main_company_selected_name: '',
    searchCompaniesSelected: [],
    customersNamesCollections: [],
    customersNameCollectionsLoading: false,
    selectedRFID: '',
    customersRFIDAssets: [],
    customersRFIDAssetsLoading: false,
    lawyerList:[],
    lawyerListLoading: false,
    documentList: [],
    documentListLoading: false,
    companyLawyerList: [],
    telephoneList: [],
    addressList: [],
    addressListLoading: false, 
    update_document_row: null,
    childCompanies: [],
    companiesList: [],
    companyListLoading: false,
    userList: [],
    userListLoading: true,
    recordItems: {},
    recordItemsLoading: false,
    treeToggle: [],
    treeExpand: [], 
    errorItems: { count:{ title: 0, address: 0, other: 0 }, list:{ invent: [], assign: [], corr: [], address: [], security: [] } },
    errorItemsLoading: false,
    searchCompanies: [],
    searchCompanyLoading: false,
    alertsCount: 0,
    messagesCount: 0,
    charts: {},
    chartsLoading: false,
    timeLine: {},
    timeLineLoading: false,
    transactions: { buy: 0, sale: 0, security: 0, release: 0, license_in: 0, license_out: 0 },
    transactionsLoading: false,
    comments: '',
    commentsLoading: false,
    screenHeight: 0,
    screenWidth: 0,
    popup_assets: {},
    display_popup_asset: 'none',
    assetLegalEvents: [],
    assetFamily: [],
    familyItem: {},
    assets: {},
    assetsLoading: false,
    assetsOutsource: {},
    assetsOutsourceLoading: false,
    validateCounter: { application: 0, patent: 0, encumbered: 0 },
    validateCounterLoading: false,
    assetsCount: { weekly_transactions: 0, weekly_applications: 0, monthly_transactions: 0, montly_applications: 0, quaterly_transactions: 0, quaterly_applications: 0 },
    assetsCountLoading: false,
    main_company_selected: false,
    tree: {}, 
    company_tree: {},
    currentAsset: '',
    currentAssetType: '',
    commentMessage: '',
    siteLogo: {},
    nestGridTab: 0,
    chartTab: 0,
    timelineTab: 0,
    errorTab: 0,
    fixitTab: 0,
    recorditTab: 0,    
    settingTab: 0,
    chart_one: [],
    chart_two: [],
    chart_three: [],
    chart_four: [], 
    chart_five: [], 
    add_years: true,
    errorTotal: 0,
    illustrationUrl: 'about:blank',
    curTree: [
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      },
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      },
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      },
      {
        curTreeLevel1: '',
        curTreeLevel2: '',
        curTreeLevel3: '',
        curTreeLevel4: ''
      }
    ],
  }
}